### ISSUE TITLE
Failing Case with Simple Data

### ISSUE THREAD

**Issue by RoyiAvital** [stelmo/LinearSegmentation.jl#5] opened 2023-07-10 13:14 UTC
Run the following script:

```julia
# External
using LinearSegmentation;
using StableRNGs;
using UnicodePlots;

## Constants & Configuration

oRng = StableRNG(123);

## Functions

function Conv1D( vA :: Vector{T}, vB :: Vector{T}; convMode :: String = "full" ) :: Vector{T} where {T <: Real}

    lenA = length(vA);
    lenB = length(vB);

    if (convMode == "full")
        startIdx    = 1;
        endIdx      = lenA + lenB - 1;
    elseif (convMode == "same")
        startIdx    = 1 + floor(Int, lenB / 2);
        endIdx      = startIdx + lenA - 1;
    elseif (convMode == "valid")
        startIdx    = lenB;
        endIdx      = lenA;
    end

    vO = zeros(T, lenA + lenB - 1);

    for idxB in 1:lenB
        @simd for idxA in 1:lenA
            @inbounds vO[idxA + idxB - 1] += vA[idxA] * vB[idxB];
        end
    end

    return vO[startIdx:endIdx];
end

## Parameters
# Data
numSamples    = 500;
ampFiltSize   = 20;
phaseFiltSize = 50;

vSeg = [1, 151, 301, 401, 501];

# Model
minSegLen = 30.0;
maxRmse   = 0.12;

## Load / Generate Data

vAmp    = rand(oRng, numSamples);
vAmp    = 0.2 * Conv1D(vAmp, ones(ampFiltSize) / ampFiltSize; convMode = "same");
vPhase  = 0.2 * rand(oRng, numSamples);
vPhase  = Conv1D(vPhase, ones(phaseFiltSize) / phaseFiltSize; convMode = "same");
vPhase  = cumsum(vPhase);

vX = LinRange(0, numSamples - 1, numSamples);

vC = vAmp .* cos.(2 * pi * vPhase);
vL = zeros(numSamples);
vL[vSeg[1]:(vSeg[2] - 1)] .= 0;
vL[vSeg[2]:(vSeg[3] - 1)] .= 1;
vL[vSeg[3]:(vSeg[4] - 1)] .= collect(LinRange(0.5, 1.0, 100));
vL[vSeg[4]:(vSeg[5] - 1)] .= collect(LinRange(1.0, 0.4, 100));

vY = vC .+ vL;

## Display Data

ii = 1;
vIdx = vSeg[ii]:(vSeg[ii + 1] - 1)

hP = scatterplot(vX[vIdx], vY[vIdx], width = 90, height = 8, xlim = (vX[1], vX[end]), ylim = (minimum(vY), maximum(vY)));

for ii in 2:(length(vSeg) - 1)
    local vIdx = vSeg[ii]:(vSeg[ii + 1] - 1)
    scatterplot!(hP, vX[vIdx], vY[vIdx]);
end

title!(hP, "Input Data");
xlabel!(hP, "Index");
ylabel!(hP, "Value");
display(hP);

## Analysis
segs = shortest_path(vX, vY; min_segment_length = minSegLen, fit_function = :rmse, fit_threshold = maxRmse);

# Remove the 1st item which is shared
for ii in 2:length(segs)
    deleteat!(segs[ii][1], 1);
end

## Display Results
hP = scatterplot(segs[1][1], vY[segs[1][1]], width = 90, height = 8, xlim = (vX[1], vX[end]), ylim = (minimum(vY), maximum(vY)));

for ii in 2:length(segs)
    scatterplot!(hP, segs[ii][1], vY[segs[ii][1]]);
end

title!(hP, "Linear Segmentation");
xlabel!(hP, "Index");
ylabel!(hP, "Value");
display(hP);
```

This is the data:

![image](https://github.com/stelmo/LinearSegmentation.jl/assets/7347975/73b86238-3f3d-46fd-905f-ffec865d9a70)

Basically an harmonic signal riding a DC and linear functions.  
Should be easy case.

The output is:

![image](https://github.com/stelmo/LinearSegmentation.jl/assets/7347975/01f76b63-8267-44be-b07a-52e9a24af0a5)

Look at the bottom left of the first linear (Rising), you see magenta colors?
The segments are:

```
The 1 segment is 1:150
The 2 segment is 151:301
The 3 segment is 302:394
The 4 segment is 395:500
```

Some overlap in 3 to 4 makes some sense, but for 2 and 3?
Under no RMSE it should be an improvement.

I think it has to do with the shortest path vs. the original idea of interval partition.
Yet I'm not sure.

**Comment by RoyiAvital** [comment] 2023-07-10 13:17
By the way, I don't see the point in having dependency on such a big package as `GLM.jl`.
It is only a linear regression, 2 lines to calculate the coefficients, why add it?

**Comment by stelmo** [comment] 2023-07-10 14:08
Thanks for the test case! I will look at it soon to see what is going on. Wrt to GLM, I wanted to include it because of all the nice statistics it gives you per fit, but you are right, it is a  heavy dep. I will think about dropping it.

**Comment by stelmo** [comment] 2023-07-10 16:32
Hmm weirdly I cannot reproduce your incorrect figure... On version 0.2.1 by running this:
```julia
# External
using LinearSegmentation
using StableRNGs
using CairoMakie, ColorSchemes

set_theme!(palette = (color = ColorSchemes.tableau_10,))


## Constants & Configuration

oRng = StableRNG(123);

## Functions

function Conv1D( vA :: Vector{T}, vB :: Vector{T}; convMode :: String = "full" ) :: Vector{T} where {T <: Real}

    lenA = length(vA);
    lenB = length(vB);

    if (convMode == "full")
        startIdx    = 1;
        endIdx      = lenA + lenB - 1;
    elseif (convMode == "same")
        startIdx    = 1 + floor(Int, lenB / 2);
        endIdx      = startIdx + lenA - 1;
    elseif (convMode == "valid")
        startIdx    = lenB;
        endIdx      = lenA;
    end

    vO = zeros(T, lenA + lenB - 1);

    for idxB in 1:lenB
        @simd for idxA in 1:lenA
            @inbounds vO[idxA + idxB - 1] += vA[idxA] * vB[idxB];
        end
    end

    return vO[startIdx:endIdx];
end

## Parameters
# Data
numSamples    = 500;
ampFiltSize   = 20;
phaseFiltSize = 50;

vSeg = [1, 151, 301, 401, 501];

# Model
minSegLen = 30.0;
maxRmse   = 0.12;

## Load / Generate Data

vAmp    = rand(oRng, numSamples);
vAmp    = 0.2 * Conv1D(vAmp, ones(ampFiltSize) / ampFiltSize; convMode = "same");
vPhase  = 0.2 * rand(oRng, numSamples);
vPhase  = Conv1D(vPhase, ones(phaseFiltSize) / phaseFiltSize; convMode = "same");
vPhase  = cumsum(vPhase);

vX = LinRange(0, numSamples - 1, numSamples);

vC = vAmp .* cos.(2 * pi * vPhase);
vL = zeros(numSamples);
vL[vSeg[1]:(vSeg[2] - 1)] .= 0;
vL[vSeg[2]:(vSeg[3] - 1)] .= 1;
vL[vSeg[3]:(vSeg[4] - 1)] .= collect(LinRange(0.5, 1.0, 100));
vL[vSeg[4]:(vSeg[5] - 1)] .= collect(LinRange(1.0, 0.4, 100));

vY = vC .+ vL;

## Display Data


fig = Figure()
ax = Axis(fig[1,1])
ii = 1;
vIdx = vSeg[ii]:(vSeg[ii + 1] - 1)
scatter!(ax, vX[vIdx], vY[vIdx])
for ii in 2:(length(vSeg) - 1)
    local vIdx = vSeg[ii]:(vSeg[ii + 1] - 1)
    scatter!(ax, vX[vIdx], vY[vIdx]);
end
fig

## Analysis
segments = shortest_path(vX, vY; min_segment_length = minSegLen, overlap=false, fit_threshold=maxRmse, fit_function=:rmse)

for (_xs, _ys) in xygroups(segments, vX)
    lines!(ax, _xs, _ys; linewidth=8)
end
fig
```
I get this output:
![temp](https://github.com/stelmo/LinearSegmentation.jl/assets/1234365/97430706-5b5d-492b-85e4-b5c4aaf1e6a6)

**Comment by stelmo** [comment] 2023-07-10 16:33
I think you missed the `overlap` option I added yesterday!

**Comment by RoyiAvital** [comment] 2023-07-10 17:47
I didn't miss it. I don't understand why would it change the operation of the solver.

I'd assume it is a step taken after the shortest path, right?

With no overlap not all points are covered:

```
The 1 segment is 1:150
The 2 segment is 152:300
The 3 segment is 302:393
The 4 segment is 395:500
```

**Comment by stelmo** [comment] 2023-07-11 05:47
No, it actually changes the weight matrix before finding the shortest path. Hmm good spot, I will investigate!

**Comment by RoyiAvital** [comment] 2023-07-11 07:01
If it is not post processing, how can the path be not contiguous?
Geometrically, I don't think _shortest path_ makes sense here.  
By definition it has to jump between segments and doesn't create the notion of segments.

It would make more sense to do Spectral Clustering on the affinity mask than do the shortest path (Normalized cuts).
There is a connection between the cut and the shortest path, but in practice, I think it might be better. 

Why not use the solution of the R package?

**Comment by stelmo** [comment] 2023-07-12 20:58
cool, so there was a small bug in `shortest_path`, which is now fixed on master. Try it out, it should generate the sensible segments in your example. I will register a new minor version asap. Implementation-wise, it does not require postprocessing, because the meaning of the nodes just changes slightly. In the non-overlapping case the right end-point is non-inclusive (and the length restrictions apply to the end of the previous node). So it really does work with the shortest path method :) 

If you want, you can implement another take on the segmentation, I'd be happy to review a PR for a new method :) 

Finally, I think the dynamic programming approach is actually quite similar to the shortest path approach taken here, but again, if you prefer that, just use those packages. However, this one seems to work, and generate sensible segments...

**Comment by RoyiAvital** [comment] 2023-07-12 21:32
@stelmo , Sound cool.

I actually implemented my own idea now based on Dynamic Programming. 
I will share a link and we'll see if we can incorporate it inside.

**Comment by stelmo** [comment] 2023-07-13 07:47
Great! Okay, I am going to close this issue, but open another one for potentially taking out the dependency on GLM. Please open a PR for your segmentation method when you have it ready!

**Closed as completed by stelmo** 2023-07-13 07:47 UTC
